"""
TATHYON Response Planner — Constrained Redistribution Engine.
BUILD PHASE 4: RESPONSE PLAN + OR-TOOLS

Solves multi-node public health redistribution under strict physical invariants:
  1. Unusable/unverified stock is strictly excluded from donor pools.
  2. Safety floors at donor facilities are unconditionally preserved.
  3. Objective hierarchy:
     - Level 1: Minimise unmet critical demand
     - Level 2: Minimise travel x quantity (ton-km)
     - Level 3: Minimise number of physical transfers
     - Level 4: Minimise expiry waste (prioritise FEFO redeployment)
  4. NOTHING is executed automatically. Every plan is generated as "PROPOSED"
     and requires authenticated Human Medical Officer approval.
"""
from __future__ import annotations

import math
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from ortools.sat.python import cp_model

from .graph import HealthcareResourceGraph, haversine_distance_km
from .schema import EventType, Provenance, ResourceType, new_id, now, sha256
from .store import EventStore
from .routing import RouteIntelligenceAdapter, RouteInfo


@dataclass
class PlanTransfer:
    """A discrete verified physical redistribution leg."""
    source: str                               # Donor Facility ID
    destination: str                          # Shortage Facility ID
    resource: str                             # Resource ID
    quantity: float                           # Units to transfer
    reason: str                               # Clinical / operational justification
    distance: float                           # Distance in km
    travel_hours: float                       # Transit time at standard rural speed
    expected_coverage: str                    # Additional days of stock delivered
    expiry_impact: str                        # Safe batch redeployment status
    risk: str                                 # Donor remaining buffer assessment
    route_risk: str = "Normal"
    data_source: str = "SYNTHETIC_HAVERSINE_ESTIMATE"

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ResponsePlan:
    """A typed response plan generated by Tathyon.
    
    Contains explicit top-level fields matching the locked specification,
    supporting both single-leg hero scenarios and multi-facility networks.
    """
    plan_id: str
    source: str
    destination: str
    resource: str
    quantity: float
    reason: str
    distance: float
    expected_coverage: str
    expiry_impact: str
    risk: str
    constraints: list[Any]
    simulation_id: Optional[str] = None
    transfers: list[PlanTransfer] = field(default_factory=list)
    counterfactuals: list[dict] = field(default_factory=list)
    total_quantity: float = 0.0
    fulfilled_qty: float = 0.0
    shortfall_qty: float = 0.0
    replan_required: bool = False
    rejected_donors: list[dict] = field(default_factory=list)
    status: str = "PROPOSED"                  # "PROPOSED" | "APPROVED" | "REJECTED" | "NO_FEASIBLE_PLAN"
    why_donor: str = ""
    why_quantity: str = ""
    why_recipient: str = ""
    why_route: str = ""
    remaining_safety_floor: float = 0.0
    predicted_outcome: str = ""
    approved_by: Optional[str] = None
    approval_role: Optional[str] = None
    approval_timestamp: Optional[str] = None
    provenance: str = "SIMULATION"
    disclaimer: str = (
        "SIMULATION / PROPOSED PLAN ONLY. "
        "NOTHING is executed automatically. "
        "Requires explicit signed Human Medical Officer approval."
    )
    system_of_record_payload: Optional[dict] = None
    created_at: str = field(default_factory=now)

    def to_dict(self) -> dict:
        d = asdict(self)
        d["transfers"] = [t.to_dict() for t in self.transfers]
        d["counterfactuals"] = self.counterfactuals
        d["rejected_donors"] = self.rejected_donors
        d["system_of_record_payload"] = self.system_of_record_payload
        d["sor_payload"] = self.system_of_record_payload
        d["why_donor"] = self.why_donor
        d["why_quantity"] = self.why_quantity
        d["why_recipient"] = self.why_recipient
        d["why_route"] = self.why_route
        d["remaining_safety_floor"] = self.remaining_safety_floor
        d["predicted_outcome"] = self.predicted_outcome
        return d


class ResponsePlanner:
    """Constrained redistribution planner powered by OR-Tools CP-SAT."""

    def __init__(self, graph: HealthcareResourceGraph, store: Optional[EventStore] = None):
        self.graph = graph
        self.store = store or graph.store
        self.router = RouteIntelligenceAdapter()

    def plan_redistribution(
        self,
        resource_id: str,
        simulation_id: Optional[str] = None,
        min_safety_days: float = 14.0,
        max_donor_fraction: float = 0.5,
        max_distance_km: float = 200.0,
        max_freshness_hours: float = 48.0,
        speed_kmph: float = 40.0,
        time_limit_s: float = 5.0,
        recipient_overrides: Optional[dict[str, dict]] = None,
        exclude_donor_ids: Optional[list[str]] = None,
        as_of: Optional[datetime] = None,
    ) -> ResponsePlan:
        """Computes optimal, safe redistribution to resolve stockouts.

        `recipient_overrides` / `exclude_donor_ids` let the rescue assessment feed this
        planner (age-adjusted stock, real bridge horizon, only on-time donors). They do not
        add a second optimizer: allocation is still this CP-SAT model.
        
        Enforces:
          - Only donor facilities with usable_quantity > safety_floor are considered.
          - Unverified or expired stock is excluded.
          - Multi-objective lexicographic hierarchy via integer scaling.
        """
        res = self.graph.resources.get(resource_id)
        criticality = res.criticality if res else 5.0
        res_name = res.name if res else resource_id

        # 1. Identify Shortage Facilities
        shortages = self.graph.get_shortage_facilities(resource_id, overrides=recipient_overrides)
        # 2. Identify Verified Donor Facilities
        donors = self.graph.get_donor_inventory(
            resource_id, min_safety_days=min_safety_days,
            max_attestation_age_hours=max_freshness_hours,
            exclude_facility_ids=exclude_donor_ids, as_of=as_of,
        )

        plan_id = f"PLAN-{now()[:10].replace('-', '')}-{new_id('plan')[:8].upper()}"
        constraints_list = [
            {"source": "Tathyon system policy (cites GFR 2017 Rule 213; citation not independently verified)", "jurisdiction": "System", "policy_type": "SYSTEM POLICY", "parameter": "only physically usable stock may move"},
            {"source": "Configurable donor reserve (NHM buffer-stock guidance not independently verified)", "jurisdiction": "System", "policy_type": "CONFIGURATION", "parameter": f"donor safety floor {min_safety_days} days / max {int(max_donor_fraction * 100)}%"},
            {"source": "Logistics Config", "jurisdiction": "District", "policy_type": "CONFIGURATION", "parameter": f"max transit distance <= {max_distance_km} km"},
            {"source": "System Default", "jurisdiction": "Global", "policy_type": "DEMO ASSUMPTION", "parameter": f"resource criticality weight = {criticality}"},
            {"source": "Tathyon system policy", "jurisdiction": "System", "policy_type": "SYSTEM POLICY", "parameter": "human medical officer approval mandatory before any shipment"},
            {"source": "Configurable freshness limit", "jurisdiction": "System", "policy_type": "CONFIGURATION", "parameter": f"data freshness <= {max_freshness_hours}h"},
        ]

        # Collect rejected donor candidates across the network
        rejected_donors: list[dict] = []
        shortage_fids = {s["facility_id"] for s in shortages}

        for (fid, rid), st in self.graph.states.items():
            if rid != resource_id or fid in shortage_fids:
                continue
            fac = self.graph.facilities.get(fid)
            fac_name = fac.name if fac else fid

            if st.usable_quantity <= 0.0:
                rejected_donors.append({
                    "facility_id": fid,
                    "facility_name": fac_name,
                    "claimed_quantity": st.claimed_quantity,
                    "usable_quantity": st.usable_quantity,
                    "reason": "Unverified physical inventory (usable_stock = 0.0; unverified stock cannot donate)",
                    "last_attested_at": st.last_attested_at,
                })
            elif not st.is_attestation_fresh(max_age_hours=max_freshness_hours, as_of=as_of):
                rejected_donors.append({
                    "facility_id": fid,
                    "facility_name": fac_name,
                    "claimed_quantity": st.claimed_quantity,
                    "usable_quantity": st.usable_quantity,
                    "reason": f"Stale physical attestation (attested {st.last_attested_at or 'missing'} older than {max_freshness_hours}h policy limit)",
                    "last_attested_at": st.last_attested_at,
                })
            elif st.get_transferable_donor_qty(min_safety_days=min_safety_days, max_age_hours=max_freshness_hours, as_of=as_of) <= 0.0:
                safety_units = round(st.consumption_velocity * min_safety_days, 1)
                rejected_donors.append({
                    "facility_id": fid,
                    "facility_name": fac_name,
                    "claimed_quantity": st.claimed_quantity,
                    "usable_quantity": st.usable_quantity,
                    "reason": f"Buffer below safety floor ({min_safety_days:.0f} days required = {safety_units} units)",
                    "last_attested_at": st.last_attested_at,
                })

        if not shortages:
            return ResponsePlan(
                plan_id=plan_id,
                source="NONE",
                destination="NONE",
                resource=resource_id,
                quantity=0.0,
                reason=f"No facilities are currently in shortage for {res_name}.",
                distance=0.0,
                expected_coverage="Adequate network inventory maintained across all nodes.",
                expiry_impact="Stock is stable within shelf-life boundaries.",
                risk="LOW",
                constraints=constraints_list,
                simulation_id=simulation_id,
                transfers=[],
                rejected_donors=rejected_donors,
                status="PROPOSED",
            )

        if not donors:
            primary_dest = shortages[0]["facility_id"]
            total_req = sum(s["shortfall_quantity"] for s in shortages)
            return ResponsePlan(
                plan_id=plan_id,
                source="NONE_AVAILABLE",
                destination=primary_dest,
                resource=resource_id,
                quantity=0.0,
                fulfilled_qty=0.0,
                shortfall_qty=round(total_req, 1),
                replan_required=True,
                reason=(
                    f"CRITICAL SHORTAGE at {primary_dest} ({shortages[0]['shortfall_quantity']} units needed), "
                    f"but NO VERIFIED DONOR has usable stock above safety floor within parameters. "
                    "Unverified stock cannot be moved; escalation to the State Drug Warehouse required."
                ),
                distance=0.0,
                expected_coverage="0 days — Emergency purchase requisition triggered.",
                expiry_impact="No inventory available for redeployment.",
                risk="CRITICAL",
                constraints=constraints_list,
                simulation_id=simulation_id,
                transfers=[],
                rejected_donors=rejected_donors,
                status="NO_FEASIBLE_PLAN",
                why_donor="None: No facility meets verified usable buffer threshold exceeding safety floor.",
                why_quantity="0 units: Zero transferable verified surplus exists in reachable network.",
                why_recipient=f"Primary shortage facility {primary_dest} requires urgent external escalation.",
                why_route="N/A: No feasible route.",
                remaining_safety_floor=0.0,
                predicted_outcome="0 days runway added; state escalation required.",
            )

        total_required = sum(s["shortfall_quantity"] for s in shortages)
        total_available = sum(d["surplus_transferable"] for d in donors)
        
        if total_available <= 0.0:
            primary_dest = shortages[0]["facility_id"]
            return ResponsePlan(
                plan_id=plan_id,
                source="NONE_AVAILABLE",
                destination=primary_dest,
                resource=resource_id,
                quantity=0.0,
                fulfilled_qty=0.0,
                shortfall_qty=round(total_required, 1),
                replan_required=True,
                reason=(
                    f"NO FEASIBLE PLAN: Network supply is insufficient. "
                    f"Required: {total_required}, Available transferable: {total_available}. "
                    f"Shortfall: {total_required - total_available} units. "
                    f"Blocking constraint: Cannot safely fulfill demand without violating safety floors."
                ),
                distance=0.0,
                expected_coverage="0 days",
                expiry_impact="N/A",
                risk="CRITICAL",
                constraints=constraints_list,
                simulation_id=simulation_id,
                transfers=[],
                rejected_donors=rejected_donors,
                status="NO_FEASIBLE_PLAN",
                why_donor="Insufficient total network transferable surplus.",
                why_quantity=f"Available ({total_available}) < Required ({total_required}).",
                why_recipient=f"Shortfall of {total_required - total_available} units.",
                why_route="N/A",
                remaining_safety_floor=0.0,
                predicted_outcome="State escalation required."
            )

        # 3. Setup OR-Tools CP-SAT Solver
        model = cp_model.CpModel()
        SCALE = 10  # 0.1 unit precision

        pairs: dict[tuple[int, int], dict[str, Any]] = {}

        for di, donor in enumerate(donors):
            d_fac = self.graph.facilities[donor["facility_id"]]
            surplus_transferable = donor["surplus_transferable"]
            max_can_give = min(surplus_transferable, donor["usable_quantity"] * max_donor_fraction)

            for si, shortage in enumerate(shortages):
                s_fac = self.graph.facilities[shortage["facility_id"]]
                if d_fac.facility_id == s_fac.facility_id:
                    continue

                # Get real-world routing and access risk intelligence
                route_info = self.router.get_route_intelligence(
                    origin_id=d_fac.facility_id,
                    dest_id=s_fac.facility_id,
                    origin_lat=d_fac.lat,
                    origin_lon=d_fac.lon,
                    dest_lat=s_fac.lat,
                    dest_lon=s_fac.lon
                )
                dist = route_info.distance_km
                travel_hrs = route_info.eta_hours
                risk_signal = route_info.access_risk
                
                # Check if route exceeds maximum transit radius
                if dist > max_distance_km:
                    continue

                # Delivery ETA Risk (Feature 7): If ETA exceeds recipient runway, reject this route.
                # Adding 0.1 as a small buffer.
                days_left = shortage["days_left"]
                if days_left > 0.0 and travel_hrs > days_left * 24.0 + 0.1:
                    rejected_donors.append({
                        "facility_id": donor["facility_id"],
                        "facility_name": donor["facility_name"],
                        "claimed_quantity": donor["claimed_quantity"],
                        "usable_quantity": donor["usable_quantity"],
                        "reason": f"DELIVERY WILL ARRIVE AFTER PROJECTED SHORTAGE (ETA {travel_hrs:.1f}h > Runway {days_left*24:.1f}h)",
                        "last_attested_at": donor.get("last_attested_at"),
                    })
                    continue

                shortfall = shortage["shortfall_quantity"]
                cap = int(min(max_can_give, shortfall) * SCALE)
                if cap <= 0:
                    continue

                pairs[(di, si)] = {
                    "var": model.NewIntVar(0, cap, f"move_{di}_{si}"),
                    "used": model.NewBoolVar(f"used_{di}_{si}"),
                    "dist": dist,
                    "travel_hours": travel_hrs,
                    "donor": donor,
                    "shortage": shortage,
                    "access_risk": risk_signal.signal_type,
                    "data_source": route_info.data_source
                }

        if not pairs:
            primary_dest = shortages[0]["facility_id"]
            for d in donors:
                rejected_donors.append({
                    "facility_id": d["facility_id"],
                    "facility_name": d["facility_name"],
                    "claimed_quantity": d["claimed_quantity"],
                    "usable_quantity": d["usable_quantity"],
                    "reason": f"Verified donor exists but exceeds maximum transit radius ({max_distance_km} km)",
                    "last_attested_at": d.get("last_attested_at"),
                })
            return ResponsePlan(
                plan_id=plan_id,
                source="OUT_OF_RANGE",
                destination=primary_dest,
                resource=resource_id,
                quantity=0.0,
                reason=f"Verified donors exist but all exceed maximum radius ({max_distance_km} km).",
                distance=0.0,
                expected_coverage="0 days",
                expiry_impact="N/A",
                risk="HIGH",
                constraints=constraints_list,
                simulation_id=simulation_id,
                transfers=[],
                rejected_donors=rejected_donors,
                status="PROPOSED",
            )

        # Link boolean indicator 'used'
        for (di, si), p in pairs.items():
            model.Add(p["var"] > 0).OnlyEnforceIf(p["used"])
            model.Add(p["var"] == 0).OnlyEnforceIf(p["used"].Not())

        # Constraint: Donor cannot exceed max transferable stock
        for di, donor in enumerate(donors):
            out_vars = [p["var"] for (d_idx, _), p in pairs.items() if d_idx == di]
            if out_vars:
                max_units = int(min(donor["surplus_transferable"], donor["usable_quantity"] * max_donor_fraction) * SCALE)
                model.Add(sum(out_vars) <= max_units)

        # Constraint: Shortage recipient cannot exceed shortfall
        unmet_vars: dict[int, Any] = {}
        for si, shortage in enumerate(shortages):
            in_vars = [p["var"] for (_, s_idx), p in pairs.items() if s_idx == si]
            need_units = int(shortage["shortfall_quantity"] * SCALE)
            u_var = model.NewIntVar(0, need_units, f"unmet_{si}")
            unmet_vars[si] = u_var
            if in_vars:
                model.Add(sum(in_vars) + u_var == need_units)
            else:
                model.Add(u_var == need_units)

        # 4. Objective Hierarchy
        # L1: minimize unmet critical demand (weight: 100,000 * criticality)
        # L2: minimize route access risk (weight: 50,000)
        # L3: minimize ETA x quantity (weight: 100)
        # L4: minimize number of discrete transfer moves (weight: 500)
        W_UNMET = int(100000 * criticality)
        W_RISK = 5000000
        W_ETA = 100
        W_MOVES = 500

        obj_terms = []
        for si, shortage in enumerate(shortages):
            # Finer granularity: base urgency 1, up to 10 based on how few days are left
            days_left = shortage["days_left"]
            if days_left <= 0.0:
                urgency = 100
            else:
                urgency = int(max(1, 100 / (days_left + 1)))
            obj_terms.append(unmet_vars[si] * (W_UNMET * urgency // 100))

        for (di, si), p in pairs.items():
            # access risk penalty
            if p["access_risk"] == "POTENTIAL ACCESS DISRUPTION":
                obj_terms.append(p["used"] * W_RISK)
            
            # ETA x quantity
            obj_terms.append(p["var"] * int(p["travel_hours"] * W_ETA))
            # transfer activation cost
            obj_terms.append(p["used"] * W_MOVES)

        model.Minimize(sum(obj_terms))

        solver = cp_model.CpSolver()
        solver.parameters.num_search_workers = 1
        solver.parameters.max_time_in_seconds = time_limit_s
        solve_status = solver.Solve(model)

        transfers: list[PlanTransfer] = []
        if solve_status in (cp_model.OPTIMAL, cp_model.FEASIBLE):
            for (di, si), p in pairs.items():
                qty = solver.Value(p["var"]) / SCALE
                if qty > 0:
                    d_info = p["donor"]
                    s_info = p["shortage"]
                    daily_vel = s_info["daily_velocity"]
                    cov_days = round(qty / daily_vel, 1) if daily_vel > 0 else 14.0

                    t = PlanTransfer(
                        source=d_info["facility_id"],
                        destination=s_info["facility_id"],
                        resource=resource_id,
                        quantity=round(qty, 1),
                        reason=(
                            f"Verified redistribution: {d_info['facility_name']} has surplus {d_info['surplus_transferable']} "
                            f"units above safety floor; {s_info['facility_name']} faces stockout in {s_info['days_left']:.1f} days."
                        ),
                        distance=round(p["dist"], 1),
                        travel_hours=p["travel_hours"],
                        expected_coverage=f"+{cov_days} days coverage",
                        expiry_impact="SAFE: Batch verified valid, FEFO rotation prioritised.",
                        risk=f"LOW: Donor retains verified buffer >= {d_info['safety_floor']} units.",
                        route_risk=p["access_risk"],
                        data_source=p["data_source"]
                    )
                    transfers.append(t)

        # Check for verified donors not selected by solver
        used_donors = {t.source for t in transfers}
        for d in donors:
            if d["facility_id"] not in used_donors:
                rejected_donors.append({
                    "facility_id": d["facility_id"],
                    "facility_name": d["facility_name"],
                    "claimed_quantity": d["claimed_quantity"],
                    "usable_quantity": d["usable_quantity"],
                    "reason": "Surplus verified, but unallocated by cost-optimal solver (closer verified donors prioritized)",
                    "last_attested_at": d.get("last_attested_at"),
                })

        if not transfers:
            primary_dest = shortages[0]["facility_id"]
            total_req = sum(s["shortfall_quantity"] for s in shortages)
            return ResponsePlan(
                plan_id=plan_id,
                source="UNRESOLVED",
                destination=primary_dest,
                resource=resource_id,
                quantity=0.0,
                fulfilled_qty=0.0,
                shortfall_qty=round(total_req, 1),
                replan_required=True,
                reason="Optimization constraints could not find a feasible verified transfer route.",
                distance=0.0,
                expected_coverage="0 days",
                expiry_impact="N/A",
                risk="HIGH",
                constraints=constraints_list,
                simulation_id=simulation_id,
                transfers=[],
                rejected_donors=rejected_donors,
                status="NO_FEASIBLE_PLAN",
                why_donor="None: Candidate donors lacked feasible routes or sufficient transferable surplus.",
                why_quantity="0 units: Solver could not fulfill shortfall under safety floor and distance bounds.",
                why_recipient=f"Shortage at {primary_dest} remains unresolved within current local bounds.",
                why_route="N/A: No transfer routes met distance constraint.",
                remaining_safety_floor=0.0,
                predicted_outcome="0 days added; requires inter-district escalation.",
            )

        # Unmet demand per shortage facility, from what the solver actually allocated.
        received: dict[str, float] = {}
        for t in transfers:
            received[t.destination] = received.get(t.destination, 0.0) + t.quantity
        unmet = [
            (sh, round(max(sh["shortfall_quantity"] - received.get(sh["facility_id"], 0.0), 0.0), 1))
            for sh in shortages
        ]
        unmet_text = "; ".join(
            f"{sh['facility_id']}: needed {sh['shortfall_quantity']}, allocated "
            f"{round(received.get(sh['facility_id'], 0.0), 1)}, UNMET {u} ({sh['days_left']:.1f} days of stock left)"
            for sh, u in unmet
        )
        total_unmet = round(sum(u for _, u in unmet), 1)

        # Primary summary fields from transfers
        primary_t = transfers[0]
        total_qty = sum(t.quantity for t in transfers)
        total_dist = sum(t.distance for t in transfers)
        total_demand = sum(s["shortfall_quantity"] for s in shortages)
        fulfilled_val = round(total_qty, 1)
        shortfall_val = round(max(0.0, total_demand - fulfilled_val), 1)
        replan_needed = shortfall_val > 1e-6
        
        # Calculate remaining safety buffer at primary donor
        d_st = self.graph.get_resource_state(primary_t.source, resource_id)
        d_usable_after = max((d_st.usable_quantity - primary_t.quantity) if d_st else 0.0, 0.0)
        d_safety_req = round(d_st.consumption_velocity * min_safety_days, 1) if d_st else 0.0

        plan = ResponsePlan(
            plan_id=plan_id,
            source=primary_t.source if len(transfers) == 1 else f"{len(transfers)} DONOR FACILITIES",
            destination=primary_t.destination if len(transfers) == 1 else f"{len(transfers)} SHORTAGE FACILITIES",
            resource=resource_id,
            quantity=round(total_qty, 1),
            fulfilled_qty=fulfilled_val,
            shortfall_qty=shortfall_val,
            replan_required=replan_needed,
            reason=f"Emergency redistribution of {round(total_qty, 1)} units {res_name} across {len(transfers)} transfer legs.",
            distance=round(total_dist, 1),
            expected_coverage=primary_t.expected_coverage if len(transfers) == 1 else f"Stockout deferred across {len(transfers)} nodes.",
            expiry_impact="SAFE: Verified batches dispatched under cold-chain compliance.",
            risk="LOW: All donor facilities preserve >= safety floor stock.",
            constraints=constraints_list,
            simulation_id=simulation_id,
            transfers=transfers,
            total_quantity=round(total_qty, 1),
            rejected_donors=rejected_donors,
            status="PROPOSED",
            why_donor=f"Selected {primary_t.source} having {d_st.usable_quantity if d_st else 0} verified usable units, retaining {d_usable_after} units (>= {d_safety_req} safety floor).",
            why_quantity=(f"Allocated {round(total_qty, 1)} units matching recipient deficit while strictly capping donor allocation at surplus. "
                          f"Total unmet across recipients: {total_unmet} units."),
            why_recipient=(f"Recipient urgency (fewest days of stock served first) -> {unmet_text}."),
            why_route=f"Road transit {primary_t.distance:.1f}km ({primary_t.travel_hours:.1f}h transit at {speed_kmph:.0f}km/h).",
            remaining_safety_floor=d_usable_after,
            predicted_outcome=f"Delivers {primary_t.expected_coverage} of critical runway at destination.",
        )

        cfs = []
        cfs.append({
            "scenario": "BASELINE: Do nothing",
            "quantity": 0.0,
            "eta": 0.0,
            "route_risk": "N/A",
            "predicted_outcome": "Stockout occurs. 0 days runway added.",
        })
        cfs.append({
            "scenario": f"PLAN A: {plan.source}",
            "quantity": plan.quantity,
            "eta": primary_t.travel_hours if transfers else 0.0,
            "route_risk": primary_t.route_risk if hasattr(primary_t, 'route_risk') else "N/A",
            "predicted_outcome": plan.predicted_outcome,
        })
        for idx, d in enumerate(plan.rejected_donors[:2]):
            cfs.append({
                "scenario": f"PLAN {chr(66+idx)}: {d['facility_name']}",
                "quantity": d['usable_quantity'],
                "eta": 0.0,
                "route_risk": "N/A",
                "predicted_outcome": "Rejected: " + d['reason']
            })
        plan.counterfactuals = cfs

        # Record plan proposal in the EventStore
        self.store.append(
            event_type=EventType.PLAN_PROPOSED,
            facility_id=plan.source,
            resource_type=ResourceType.MEDICINE,
            resource_key=plan.resource,
            payload={
                "plan_id": plan.plan_id,
                "resource_id": plan.resource,
                "total_quantity": plan.quantity,
                "num_transfers": len(plan.transfers),
                "simulation_id": plan.simulation_id,
            },
            actor="TathyonResponsePlanner",
        )

        return plan

    def orchestrate(
        self,
        resource_id: str,
        district: Optional[str] = None,
        as_of: Optional[Any] = None,
        visit_budget: int = 20,
        candidates: Optional[Any] = None,
        approver_id: Optional[str] = None,
        approver_role: Optional[str] = None,
        notes: str = "Authorized by Medical Officer",
    ) -> dict[str, Any]:
        """Thin orchestration pipeline:
        trust-score -> target verifications -> forecast -> allocate -> approval.
        No new decision logic.
        """
        # 1. Trust-score & Target Verifications
        from .verify import target_verifications
        v_queue = target_verifications(budget=visit_budget, candidates=candidates, as_of=as_of)

        # 2. Forecast burn-rate and expiry
        import numpy as np
        from .forecast import facility_sku_expiry_clock
        forecasts = {}
        for (fid, rid), st in self.graph.states.items():
            if rid == resource_id:
                vel = st.consumption_velocity or 5.0
                usable = st.usable_quantity or 0.0
                burn_info = facility_sku_expiry_clock(
                    facility_id=fid,
                    sku=rid,
                    issued_history=np.array([vel] * 14, dtype=float),
                    current_stock=usable,
                    as_of=as_of,
                )
                forecasts[fid] = burn_info

        # 3. Allocate: Constrained network solve
        plan = self.plan_redistribution(resource_id=resource_id, as_of=as_of)

        # 4. Approval (if approver credentials provided)
        if approver_id and approver_role and plan.status == "PROPOSED" and plan.quantity > 0:
            plan = self.approve_plan(plan, officer_id=approver_id, role=approver_role, notes=notes)

        return {
            "resource_id": resource_id,
            "district": district,
            "verification_queue": v_queue,
            "forecasts": forecasts,
            "plan": plan,
            "approved": plan.status == "APPROVED",
            "sor_payload": plan.system_of_record_payload if plan.status == "APPROVED" else None,
            "provenance": "SYNTHETIC",
        }

    def generate_sor_payload(
        self,
        plan: ResponsePlan,
        officer_id: str,
        role: str,
        notes: str = "Authorized by Medical Officer",
    ) -> dict:
        """Generates an interoperable dispatch order payload formatted for upstream
        systems of record (e-Aushadhi / DVDMS / HMIS).
        
        Tathyon acts as a resilience and verification sidecar: once approved by the CMO,
        it outputs the canonical payload for the upstream system of record to execute.
        """
        voucher_id = f"DISPATCH-TR-{plan.plan_id.replace('PLAN-', '')[:12]}"
        transfers_payload = []
        for i, t in enumerate(plan.transfers):
            s_fac = self.graph.facilities.get(t.source)
            d_fac = self.graph.facilities.get(t.destination)
            transfers_payload.append({
                "leg_id": f"LEG-{i+1:02d}",
                "donor_facility_code": t.source,
                "donor_facility_name": s_fac.name if s_fac else t.source,
                "donor_district": s_fac.district if s_fac else "Bastar",
                "recipient_facility_code": t.destination,
                "recipient_facility_name": d_fac.name if d_fac else t.destination,
                "recipient_district": d_fac.district if d_fac else "Bastar",
                "resource_sku": t.resource,
                "transfer_quantity": t.quantity,
                "transit_distance_km": t.distance,
                "estimated_transit_hours": t.travel_hours,
                "cold_chain_required": "VACCINE" in t.resource or "OXYTOCIN" in t.resource,
                "dispatch_priority": "EMERGENCY_REDISTRIBUTION",
            })

        seal = sha256(f"{voucher_id}:{plan.plan_id}:{officer_id}:{plan.quantity}:{now()}")

        return {
            "format": "READY_FOR_SYSTEM_OF_RECORD",
            "status": "READY_FOR_SYSTEM_OF_RECORD",
            "version": "1.0.0",
            "voucher_id": voucher_id,
            "plan_id": plan.plan_id,
            "resource": plan.resource,
            "donor": plan.source,
            "recipient": plan.destination,
            "quantity": plan.quantity,
            "priority": "EMERGENCY_REDISTRIBUTION",
            "route": {
                "total_distance_km": plan.distance,
                "total_legs": len(plan.transfers),
            },
            "approval": {
                "officer_id": officer_id,
                "role": role,
                "authority_type": "AUTHORIZED_HUMAN_APPROVAL",
                "notes": notes,
                "approval_timestamp": plan.approval_timestamp or now(),
            },
            "approving_officer": {
                "officer_id": officer_id,
                "role": role,
                "authority_type": "AUTHORIZED_HUMAN_APPROVAL",
                "notes": notes,
                "approval_timestamp": plan.approval_timestamp or now(),
            },
            "timestamp": now(),
            "policy_authority": "AUTHORIZED_HUMAN_APPROVAL",
            "transfer_summary": {
                "plan_id": plan.plan_id,
                "resource_id": plan.resource,
                "total_quantity": plan.quantity,
                "total_legs": len(plan.transfers),
                "total_distance_km": plan.distance,
            },
            "line_items": transfers_payload,
            "target_system_adapters": [
                {"system": "e-Aushadhi (Standard Transfer Schema)", "format": "JSON_DISPATCH_ORDER", "status": "READY_FOR_SYSTEM_OF_RECORD"},
                {"system": "DVDMS (State Health Portal)", "format": "JSON_DISPATCH_ORDER", "status": "READY_FOR_SYSTEM_OF_RECORD"},
            ],
            "integrity_hash": seal,
            "provenance": "AUTHORIZED_HUMAN_APPROVAL",
        }

    def approve_plan(
        self,
        plan: ResponsePlan,
        officer_id: str,
        role: str,
        notes: str = "Authorized by Medical Officer",
    ) -> ResponsePlan:
        """Human approval step. NOTHING executes without this call.
        
        Appends plan_approved event into the cryptographic EventStore,
        and generates the System-of-Record Payload ready for e-Aushadhi / DVDMS.
        """
        if plan.status == "APPROVED":
            raise ValueError(f"Plan '{plan.plan_id}' has already been approved (duplicate approval prevented).")
        if plan.status == "NO_FEASIBLE_PLAN" or plan.quantity <= 0.0:
            raise ValueError(f"Cannot approve unfeasible or empty plan '{plan.plan_id}'.")

        plan.status = "APPROVED"
        plan.approved_by = officer_id
        plan.approval_role = role
        plan.approval_timestamp = now()
        sor_payload = self.generate_sor_payload(plan, officer_id, role, notes)
        plan.system_of_record_payload = sor_payload

        self.store.append(
            event_type=EventType.PLAN_APPROVED,
            facility_id=plan.source,
            resource_type=ResourceType.MEDICINE,
            resource_key=plan.resource,
            payload={
                "plan_id": plan.plan_id,
                "approved_by": officer_id,
                "role": role,
                "notes": notes,
                "total_quantity": plan.quantity,
                "transfers": [t.to_dict() for t in plan.transfers],
                "sor_voucher_id": sor_payload.get("voucher_id"),
                "integrity_hash": sor_payload.get("integrity_hash"),
            },
            actor=f"{role}:{officer_id}",
        )

        return plan

    def record_outcome(
        self,
        plan_id: str,
        actual_delivered_qty: float,
        response_time_hours: float,
        outcome_status: str = "SUCCESSFUL",
        stockout_prevented: bool = True,
        notes: str = "",
        plan: Optional[ResponsePlan] = None,
    ) -> dict:
        """Records physical execution outcome and updates operational resource graph."""
        payload = {
            "plan_id": plan_id,
            "actual_delivered_qty": actual_delivered_qty,
            "response_time_hours": response_time_hours,
            "outcome_status": outcome_status,
            "stockout_prevented": stockout_prevented,
            "notes": notes,
            "recorded_at": now(),
            "provenance": "OBSERVED",
        }

        # Apply physical ground truth update to the Resource Graph if plan is provided
        if plan and plan.transfers:
            for t in plan.transfers:
                rec_st = self.graph.get_resource_state(t.destination, t.resource)
                if rec_st:
                    # Update verified physical stock
                    rec_st.usable_quantity = round(rec_st.usable_quantity + actual_delivered_qty, 1)
                    rec_st.observed_quantity = round(rec_st.observed_quantity + actual_delivered_qty, 1)
                    rec_st.incoming_quantity = max(round(rec_st.incoming_quantity - t.quantity, 1), 0.0)
                    rec_st.last_attested_at = now()
                    # Recalculate operational runway and risk
                    if rec_st.consumption_velocity > 0:
                        runway = rec_st.usable_quantity / rec_st.consumption_velocity
                        rec_st.risk = "CRITICAL" if runway <= 1.0 else ("HIGH" if runway <= 3.0 else ("MEDIUM" if runway <= 7.0 else "LOW"))

        self.store.append(
            event_type=EventType.OUTCOME_RECORDED,
            facility_id="NETWORK",
            resource_type=ResourceType.MEDICINE,
            resource_key=plan_id,
            payload=payload,
            actor="ExecutionAdapter",
        )

        return payload


# --------------------------------------------------------------------------
# Plan Explorer: Multi-Objective Plan Generation
# --------------------------------------------------------------------------

class PlanExplorer:
    """Generates multiple candidate redistribution plans with different objectives.
    
    The operator sees tradeoffs and chooses. TATHYON does NOT auto-select.
    
    PLAN_A: Closest Donor — minimize total distance
    PLAN_B: Highest Coverage — maximize demand fulfillment
    PLAN_C: Lowest Logistics Cost — minimize ₹
    PLAN_D: Highest Resilience — maximize remaining network buffer
    """

    def __init__(self, graph: HealthcareResourceGraph, store: Optional[EventStore] = None):
        self.graph = graph
        self.store = store or graph.store

    def explore_plans(
        self,
        resource_id: str,
        min_safety_days: float = 14.0,
        max_distance_km: float = 250.0,
        speed_kmph: float = 40.0,
    ) -> dict:
        """Generates 4 candidate plans with different optimization strategies."""
        planner = ResponsePlanner(self.graph, self.store)

        shortages = self.graph.get_shortage_facilities(resource_id)
        donors = self.graph.get_donor_inventory(resource_id, min_safety_days=min_safety_days)

        if not shortages or not donors:
            return {
                "status": "NO_PLANS_POSSIBLE",
                "reason": "No shortages exist or no verified donors available.",
                "shortages_count": len(shortages),
                "donors_count": len(donors),
                "plans": [],
            }

        plans = []

        # PLAN A: Closest Donor (minimize distance)
        plan_a = self._build_plan(
            "PLAN_A_CLOSEST_DONOR",
            "Minimize total transport distance",
            shortages, donors, resource_id,
            sort_key=lambda d, s: self.graph.distance_km(d["facility_id"], s["facility_id"]),
            min_safety_days=min_safety_days,
            max_distance_km=max_distance_km,
            speed_kmph=speed_kmph,
        )
        plans.append(plan_a)

        # PLAN B: Highest Coverage (maximize demand fulfillment)
        plan_b = self._build_plan(
            "PLAN_B_MAX_COVERAGE",
            "Maximize total demand fulfillment across shortage facilities",
            shortages, donors, resource_id,
            sort_key=lambda d, s: -d["surplus_transferable"],  # Largest surplus first
            min_safety_days=min_safety_days,
            max_distance_km=max_distance_km,
            speed_kmph=speed_kmph,
        )
        plans.append(plan_b)

        # PLAN C: Lowest Cost (minimize cost = distance * 25 + handling)
        plan_c = self._build_plan(
            "PLAN_C_LOWEST_COST",
            "Minimize logistics cost (₹25/km + ₹200/transfer)",
            shortages, donors, resource_id,
            sort_key=lambda d, s: self.graph.distance_km(d["facility_id"], s["facility_id"]) * 25.0 + 200.0,
            min_safety_days=min_safety_days,
            max_distance_km=max_distance_km,
            speed_kmph=speed_kmph,
        )
        plans.append(plan_c)

        # PLAN D: Highest Resilience (maximize remaining donor buffer)
        plan_d = self._build_plan(
            "PLAN_D_MAX_RESILIENCE",
            "Maximize remaining network buffer post-redistribution",
            shortages, donors, resource_id,
            sort_key=lambda d, s: -(d["days_of_stock"] - min_safety_days),  # Most buffered donor first
            min_safety_days=min_safety_days,
            max_distance_km=max_distance_km,
            speed_kmph=speed_kmph,
            max_donor_fraction=0.30,  # More conservative extraction
        )
        plans.append(plan_d)

        # Add comparison metrics
        return {
            "status": "PLANS_GENERATED",
            "shortages_count": len(shortages),
            "donors_count": len(donors),
            "resource_id": resource_id,
            "plans": plans,
            "tradeoff_matrix": self._build_tradeoff_matrix(plans),
            "decision_note": (
                "Four candidate plans generated with different optimization objectives. "
                "Examine the tradeoff matrix to understand what each plan sacrifices. "
                "The operator must select based on operational priorities."
            ),
            "provenance": "SIMULATION",
        }

    def _build_plan(
        self,
        plan_name: str,
        objective: str,
        shortages: list[dict],
        donors: list[dict],
        resource_id: str,
        sort_key,
        min_safety_days: float,
        max_distance_km: float,
        speed_kmph: float,
        max_donor_fraction: float = 0.50,
    ) -> dict:
        """Builds a single candidate plan using greedy allocation with given sort key."""
        transfers = []
        used_donor_qty = {d["facility_id"]: 0.0 for d in donors}
        total_covered = 0.0
        total_shortfall = sum(s["shortfall_quantity"] for s in shortages)

        for shortage in sorted(shortages, key=lambda s: s["days_left"]):
            remaining_need = shortage["shortfall_quantity"]
            s_fid = shortage["facility_id"]

            # Rank donors by objective-specific sort key
            ranked_donors = sorted(donors, key=lambda d: sort_key(d, shortage))

            for donor in ranked_donors:
                if remaining_need <= 0:
                    break
                d_fid = donor["facility_id"]
                if d_fid == s_fid:
                    continue

                dist = self.graph.distance_km(d_fid, s_fid)
                if dist > max_distance_km:
                    continue

                available = min(
                    donor["surplus_transferable"] * max_donor_fraction - used_donor_qty.get(d_fid, 0.0),
                    remaining_need,
                )
                if available <= 0:
                    continue

                qty = round(available, 1)
                used_donor_qty[d_fid] = used_donor_qty.get(d_fid, 0.0) + qty
                remaining_need -= qty
                total_covered += qty

                transfers.append({
                    "source": d_fid,
                    "source_name": donor["facility_name"],
                    "destination": s_fid,
                    "destination_name": shortage["facility_name"],
                    "quantity": qty,
                    "distance_km": round(dist, 1),
                    "travel_hours": round(dist / speed_kmph, 1),
                })

        total_distance = sum(t["distance_km"] for t in transfers)
        total_qty = sum(t["quantity"] for t in transfers)
        cost = round(total_distance * 25.0 + len(transfers) * 200.0, 2)
        coverage_pct = round(total_covered / max(total_shortfall, 1.0) * 100, 1)

        # Calculate remaining network buffer
        remaining_buffer_days = []
        for donor in donors:
            d_fid = donor["facility_id"]
            used = used_donor_qty.get(d_fid, 0.0)
            remaining_usable = donor["usable_quantity"] - used
            vel = self.graph.get_resource_state(d_fid, resource_id)
            vel_rate = vel.consumption_velocity if vel else 1.0
            remaining_buffer_days.append(
                round(remaining_usable / max(vel_rate, 0.1), 1)
            )
        avg_remaining_buffer = round(
            sum(remaining_buffer_days) / max(len(remaining_buffer_days), 1), 1
        )

        return {
            "plan_name": plan_name,
            "objective": objective,
            "transfers": transfers,
            "total_quantity": round(total_qty, 1),
            "total_distance_km": round(total_distance, 1),
            "total_cost_inr": cost,
            "coverage_pct": coverage_pct,
            "transfers_count": len(transfers),
            "avg_remaining_donor_buffer_days": avg_remaining_buffer,
            "shortfall_remaining": round(max(total_shortfall - total_covered, 0.0), 1),
        }

    @staticmethod
    def _build_tradeoff_matrix(plans: list[dict]) -> list[dict]:
        """Builds a comparison matrix showing what each plan sacrifices."""
        matrix = []
        for p in plans:
            matrix.append({
                "plan": p["plan_name"],
                "objective": p["objective"],
                "coverage_pct": p["coverage_pct"],
                "distance_km": p["total_distance_km"],
                "cost_inr": p["total_cost_inr"],
                "transfers": p["transfers_count"],
                "remaining_buffer_days": p["avg_remaining_donor_buffer_days"],
                "unmet_shortfall": p["shortfall_remaining"],
            })
        return matrix

