"""Option generation over one SKU: needs -> candidate plans -> recommendation.

All quantities come from the workspace projection and the CP-SAT solve in
optimize.py. Nothing in this module is learned or generated by a language
model. The recommendation rule is a short, printed policy, not a score.

Options produced for every planning cycle:
  TRUST_REPORTED         what a naive system does (solver trusts every report).
                         Always shown, never approvable: it is the counterfactual.
  TRANSFER_VERIFIED_NOW  verification-gated solve: only VERIFIED stock above floor.
  VERIFY_THEN_TRANSFER   same solve with unverified donors admitted as
                         CONTINGENT lines that cannot dispatch until a human
                         count confirms them.
  ESCALATE               the gated shortfall that no verified donor can cover.
  WAIT                   no facility is below the alert runway.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any, Optional

from .optimize import Decision, Facility, Need, SourceStock, naive_optimise, optimise
from .schema import VerificationState

KM_PER_DEG_LAT = 111.0


@dataclass(frozen=True)
class PlanningPolicy:
    horizon_days: float = 14.0             # a need tops the recipient up to this many days
    alert_runway_days: float = 7.0         # below this, a facility is a recipient
    donor_floor_days: float = 14.0         # donor keeps this many days of its own use
    max_donor_fraction: float = 1.0        # of above-floor stock; the floor is the protection
    truck_capacity: float = 5000.0
    max_travel_hours: float = 8.0
    max_cold_chain_hours: float = 8.0
    verification_turnaround_hours: float = 6.0
    decision_margin_hours: float = 12.0    # recipient must outlast verify + travel + this
    contingent_travel_saving: float = 0.25  # contingent must save >= 25% qty-weighted travel


def project_xy(lat: float, lon: float, ref_lat: float, ref_lon: float) -> tuple[float, float]:
    """Equirectangular km offsets. Adequate for district scale (< 200 km)."""
    x = (lon - ref_lon) * KM_PER_DEG_LAT * math.cos(math.radians(ref_lat))
    y = (lat - ref_lat) * KM_PER_DEG_LAT
    return round(x, 3), round(y, 3)


def weighted_travel(decision: Decision) -> float:
    return round(sum(t.qty * t.travel_hours for t in decision.transfers), 2)


def _lines(decision: Decision, unverified: set[str], prefix: str) -> list[dict]:
    out = []
    for i, t in enumerate(sorted(decision.transfers, key=lambda t: (t.from_facility, t.to_facility))):
        contingent = t.from_facility in unverified
        out.append({
            "line_id": f"{prefix}-L{i + 1}",
            "from_facility": t.from_facility,
            "to_facility": t.to_facility,
            "sku": t.resource_key,
            "qty": t.qty,
            "travel_hours": t.travel_hours,
            "distance_km": t.distance_km,
            "cold_chain": t.cold_chain,
            "kind": "CONTINGENT_ON_VERIFICATION" if contingent else "IMMEDIATE",
            "status": "PROPOSED",
            "route_provenance": "SYNTHETIC_ESTIMATE_STRAIGHT_LINE_X1.35",
        })
    return out


def _option(name: str, label: str, decision: Optional[Decision], lines: list[dict],
            approvable: bool, why: str, total_need: float) -> dict:
    fulfilled = round(sum(l["qty"] for l in lines), 1)
    return {
        "option": name,
        "label": label,
        "approvable": approvable,
        "fulfilled_qty": fulfilled,
        "shortfall_qty": round(max(total_need - fulfilled, 0.0), 1),
        "qty_weighted_travel_hours": round(sum(l["qty"] * l["travel_hours"] for l in lines), 1),
        "solver_status": decision.solver_status if decision else None,
        "lines": lines,
        "why": why,
    }


def generate_options(sku: str, facilities: dict[str, Facility], sources: list[SourceStock],
                     needs: list[Need], policy: PlanningPolicy,
                     min_recipient_runway_hours: Optional[float]) -> dict[str, Any]:
    """Solve the cycle three ways and apply the printed recommendation rule."""
    total_need = round(sum(n.shortfall for n in needs), 1)
    if not needs:
        wait = _option("WAIT", "No facility below alert runway", None, [], True,
                       "Every reporting facility is above the alert runway. Monitor.", 0.0)
        return {"options": [wait], "recommended": "WAIT", "rule": "NO_OPEN_NEED",
                "gated": None, "naive": None, "rejected_donors": [], "total_need": 0.0}

    kw = dict(max_travel_hours=policy.max_travel_hours,
              max_cycle_truck_capacity=policy.truck_capacity,
              max_donor_fraction=policy.max_donor_fraction,
              max_cold_chain_hours=policy.max_cold_chain_hours)
    unverified = {s.facility_id for s in sources if s.verified_state != VerificationState.VERIFIED}

    gated = optimise(facilities, sources, needs, **kw)
    naive = naive_optimise(facilities, sources, needs, **kw)
    promoted = [
        SourceStock(facility_id=s.facility_id, resource_key=s.resource_key, reported_qty=s.reported_qty,
                    verified_state=VerificationState.VERIFIED, q_alpha=s.reported_qty,
                    safety_stock=s.safety_stock, available=s.available)
        if s.facility_id in unverified and s.available else s
        for s in sources
    ]
    contingent = optimise(facilities, promoted, needs, **kw)

    gated_lines = _lines(gated, set(), "G") if gated.allowed else []
    naive_lines = _lines(naive, set(), "N") if naive.allowed else []
    cont_lines = _lines(contingent, unverified, "C") if contingent.allowed else []
    uses_unverified = any(l["kind"] == "CONTINGENT_ON_VERIFICATION" for l in cont_lines)

    unverified_naive_qty = round(sum(l["qty"] for l in naive_lines if l["from_facility"] in unverified), 1)
    options = [
        _option("TRUST_REPORTED", "Trust reported stock (naive counterfactual)", naive, naive_lines, False,
                f"Would move {unverified_naive_qty:g} units from facilities with no current physical "
                "count. Blocked by the verification gate; shown only as the counterfactual.", total_need),
        _option("TRANSFER_VERIFIED_NOW", "Transfer verified stock now", gated, gated_lines,
                bool(gated_lines),
                "Only physically verified stock above each donor's floor is used." if gated_lines else
                "No verified donor can supply this need under the constraints.", total_need),
    ]
    if uses_unverified:
        options.append(_option(
            "VERIFY_THEN_TRANSFER", "Verify suspect donor, then transfer", contingent, cont_lines, True,
            "Lines from unverified donors are held until a human count confirms them; "
            "verified lines can dispatch immediately.", total_need))

    gated_short = round(max(total_need - sum(l["qty"] for l in gated_lines), 0.0), 1)
    if gated_short > 0:
        options.append(_option("ESCALATE", "Escalate unmet need to state warehouse", None, [], True,
                               f"{gated_short:g} units cannot be covered by verified stock in the district.",
                               total_need))

    recommended, rule = _recommend(options, policy, min_recipient_runway_hours, cont_lines)
    return {
        "options": options,
        "recommended": recommended,
        "rule": rule,
        "gated": gated,
        "naive": naive,
        "rejected_donors": _dedupe_rejections(gated.rejected_donors),
        "total_need": total_need,
    }


def _recommend(options: list[dict], policy: PlanningPolicy,
               min_runway_h: Optional[float], cont_lines: list[dict]) -> tuple[str, str]:
    by = {o["option"]: o for o in options}
    gated, cont = by.get("TRANSFER_VERIFIED_NOW"), by.get("VERIFY_THEN_TRANSFER")
    if cont:
        slowest = max((l["travel_hours"] for l in cont_lines if l["kind"] != "IMMEDIATE"), default=0.0)
        time_ok = (min_runway_h is not None and
                   min_runway_h > policy.verification_turnaround_hours + slowest + policy.decision_margin_hours)
        g_travel = gated["qty_weighted_travel_hours"] if gated and gated["lines"] else math.inf
        saves = cont["qty_weighted_travel_hours"] <= (1 - policy.contingent_travel_saving) * g_travel
        covers_more = cont["fulfilled_qty"] > (gated["fulfilled_qty"] if gated else 0.0)
        if time_ok and (saves or covers_more):
            return "VERIFY_THEN_TRANSFER", (
                "RUNWAY_ALLOWS_VERIFICATION_AND_CONTINGENT_SAVES_TRAVEL" if saves
                else "RUNWAY_ALLOWS_VERIFICATION_AND_CONTINGENT_COVERS_MORE")
    if gated and gated["lines"]:
        return "TRANSFER_VERIFIED_NOW", ("VERIFIED_SUPPLY_AVAILABLE" if gated["shortfall_qty"] == 0
                                         else "VERIFIED_SUPPLY_PARTIAL_ESCALATE_REMAINDER")
    return "ESCALATE", "NO_VERIFIED_SUPPLY"


def _dedupe_rejections(rejected: list[dict]) -> list[dict]:
    seen, out = set(), []
    for r in rejected:
        key = (r.get("facility_id"), r.get("recipient"), r.get("reason"))
        if key not in seen:
            seen.add(key)
            out.append(r)
    return out
