"""
Shipment telemetry adapters. Three states only, never blended:

  LIVE_EXTERNAL      positions actually received from a configured tracker/server (Traccar)
  SIMULATED          points generated by Tathyon along a route, permanently labelled
  NOT_CONFIGURED     nothing configured: there is NO position and NO animation

Reality check (researched 2026-09-21): no public feed of road-vehicle positions exists.
A real position needs a physical GNSS tracker on the vehicle plus a server such as Traccar.
Satellite imagery cannot provide one. So without a configured tracker the honest answer is
"last known location: NOT AVAILABLE".

StaleFilter: a real position older than `stale_after_minutes` is reported STALE with its age;
it is never silently refreshed, and never interpolated into a "current" position. If a caller
wants a position between fixes it must request an ESTIMATE, which is labelled ESTIMATED.
"""
from __future__ import annotations

import base64
import json
import urllib.parse
import urllib.request
from dataclasses import asdict, dataclass
from datetime import datetime, timedelta, timezone
from typing import Callable, Optional

from .integrations import LIVE_EXTERNAL, NOT_CONFIGURED, SIMULATION, STALE, ESTIMATED

SIMULATED_LABEL = "SIMULATED TELEMETRY"
DEFAULT_STALE_MINUTES = 30.0        # CONFIGURATION, not a standard


@dataclass(frozen=True)
class TelemetryPoint:
    timestamp: str
    lat: float
    lon: float
    provenance: str                 # LIVE_EXTERNAL | SIMULATION | ESTIMATED
    source: str
    speed_kmh: Optional[float] = None
    temperature_c: Optional[float] = None    # only when a real sensor reports it; never invented
    battery_pct: Optional[float] = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class TelemetryReport:
    state: str                      # LIVE_EXTERNAL | STALE | SIMULATION | NOT_CONFIGURED
    label: str
    points: list[TelemetryPoint]
    last_timestamp: Optional[str]
    age_minutes: Optional[float]
    message: str

    def to_dict(self) -> dict:
        d = asdict(self)
        d["points"] = [p.to_dict() for p in self.points]
        return d


def _ts(v: str) -> datetime:
    dt = datetime.fromisoformat(v.replace("Z", "+00:00"))
    return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)


def classify(points: list[TelemetryPoint], now: datetime,
             stale_after_minutes: float = DEFAULT_STALE_MINUTES) -> TelemetryReport:
    """Turn real points into an honest report. Empty input is NOT_CONFIGURED/no data, not a guess."""
    if not points:
        return TelemetryReport(NOT_CONFIGURED, "TELEMETRY: NOT AVAILABLE", [], None, None,
                               "No position has been received. LAST KNOWN LOCATION: NOT AVAILABLE.")
    pts = sorted(points, key=lambda p: p.timestamp)
    age = (now - _ts(pts[-1].timestamp)).total_seconds() / 60.0
    if age > stale_after_minutes:
        return TelemetryReport(STALE, f"TELEMETRY STALE ({age:.0f} min old)", pts, pts[-1].timestamp,
                               round(age, 1), f"Last telemetry {age:.0f} minutes ago. Position is not current.")
    return TelemetryReport(LIVE_EXTERNAL, "LIVE TELEMETRY", pts, pts[-1].timestamp, round(age, 1),
                           "Positions received from the configured tracker.")


class TraccarAdapter:
    """Reads positions from a Traccar server (https://www.traccar.org, Apache-2.0).

    STATUS: unit-tested against a fake transport only. It has NEVER been run against a real
    Traccar server or device, so it must not be described as verified integration.
    """

    def __init__(self, base_url: Optional[str], user: Optional[str] = None, password: Optional[str] = None,
                 get: Optional[Callable[[str, dict], str]] = None):
        self.base_url = base_url.rstrip("/") if base_url else None
        self._auth = None
        if user and password:
            self._auth = "Basic " + base64.b64encode(f"{user}:{password}".encode()).decode()
        self._get = get or self._http_get

    @property
    def configured(self) -> bool:
        return bool(self.base_url)

    def _http_get(self, url: str, headers: dict) -> str:
        req = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(req, timeout=15) as r:                # noqa: S310
            return r.read().decode()

    def positions(self, device_id: int, start: datetime, end: datetime) -> list[TelemetryPoint]:
        if not self.configured:
            return []
        q = urllib.parse.urlencode({"deviceId": device_id,
                                    "from": start.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                                    "to": end.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")})
        headers = {"Accept": "application/json"}
        if self._auth:
            headers["Authorization"] = self._auth
        out = []
        for p in json.loads(self._get(f"{self.base_url}/api/positions?{q}", headers)):
            if p.get("latitude") is None or p.get("longitude") is None or not p.get("fixTime"):
                continue                                                   # never fill in missing fixes
            attrs = p.get("attributes") or {}
            speed_knots = p.get("speed")
            out.append(TelemetryPoint(
                timestamp=p["fixTime"], lat=float(p["latitude"]), lon=float(p["longitude"]),
                provenance=LIVE_EXTERNAL, source="TRACCAR",
                speed_kmh=None if speed_knots is None else round(float(speed_knots) * 1.852, 1),
                temperature_c=attrs.get("temp1") if isinstance(attrs.get("temp1"), (int, float)) else None,
                battery_pct=attrs.get("batteryLevel") if isinstance(attrs.get("batteryLevel"), (int, float)) else None,
            ))
        return out


def simulate_along_route(geometry: tuple, dispatched_at: datetime, duration_hours: float, now: datetime,
                         step_minutes: float = 15.0) -> list[TelemetryPoint]:
    """SIMULATED positions along a route, one per `step_minutes` up to `now`.

    Every point is labelled SIMULATION / "SIMULATED TELEMETRY". This exists only for demo mode.
    It moves at constant speed along the road geometry, which is a model, not an observation.
    """
    if len(geometry) < 2 or duration_hours <= 0 or now < dispatched_at:
        return []
    seg = [_hav(geometry[i], geometry[i + 1]) for i in range(len(geometry) - 1)]
    total = sum(seg)
    if total <= 0:
        return []
    pts, t = [], dispatched_at
    end = dispatched_at + timedelta(hours=duration_hours)
    while t <= min(now, end):
        frac = (t - dispatched_at).total_seconds() / (duration_hours * 3600.0)
        lon, lat = _at_fraction(geometry, seg, total, frac)
        pts.append(TelemetryPoint(t.astimezone(timezone.utc).isoformat(), lat, lon, SIMULATION,
                                  SIMULATED_LABEL, speed_kmh=round(total / duration_hours, 1)))
        t += timedelta(minutes=step_minutes)
    return pts


def _hav(a, b) -> float:
    import math
    (lo1, la1), (lo2, la2) = a, b
    dla, dlo = math.radians(la2 - la1), math.radians(lo2 - lo1)
    h = math.sin(dla / 2) ** 2 + math.cos(math.radians(la1)) * math.cos(math.radians(la2)) * math.sin(dlo / 2) ** 2
    return 6371.0 * 2 * math.atan2(math.sqrt(h), math.sqrt(1 - h))


def _at_fraction(geometry, seg, total, frac: float):
    target = max(0.0, min(frac, 1.0)) * total
    run = 0.0
    for i, s in enumerate(seg):
        if run + s >= target:
            f = 0 if s == 0 else (target - run) / s
            (lo1, la1), (lo2, la2) = geometry[i], geometry[i + 1]
            return lo1 + (lo2 - lo1) * f, la1 + (la2 - la1) * f
        run += s
    return geometry[-1]


def simulated_report(points: list[TelemetryPoint]) -> TelemetryReport:
    if not points:
        return TelemetryReport(NOT_CONFIGURED, "TELEMETRY: NOT AVAILABLE", [], None, None,
                               "Simulation has produced no points yet (shipment not dispatched).")
    return TelemetryReport(SIMULATION, SIMULATED_LABEL, points, points[-1].timestamp, None,
                           "Points are generated by Tathyon along the route. This is NOT a real vehicle position.")


def estimated_position(geometry: tuple, dispatched_at: datetime, duration_hours: float,
                       now: datetime) -> Optional[TelemetryPoint]:
    """A single ESTIMATED position from schedule alone (no tracker). Labelled ESTIMATED, never live."""
    pts = simulate_along_route(geometry, dispatched_at, duration_hours, now, step_minutes=1e9)
    if not pts:
        return None
    seg = [_hav(geometry[i], geometry[i + 1]) for i in range(len(geometry) - 1)]
    frac = min((now - dispatched_at).total_seconds() / (duration_hours * 3600.0), 1.0)
    lon, lat = _at_fraction(geometry, seg, sum(seg), frac)
    return TelemetryPoint(now.astimezone(timezone.utc).isoformat(), lat, lon, ESTIMATED,
                          "SCHEDULE_ESTIMATE (no tracker)")
