"""
TATHYON — Real-Data Pipeline Hardening & Reality Audit Test Suite.

Verifies strict scientific, sovereign, and anti-leakage doctrines:
1. Data Lineage & Provenance: detects generator simulations vs sovereign exports.
2. Label Provenance Refusal:
   - Custodian self-attestation rejected (separation of duties).
   - Unauthorized attester role rejected.
   - Anti-rubber-stamping minimum time (< 20s) rejected.
   - Usable exceeding present count rejected.
   - P6 threshold mathematical contradiction rejected.
3. Strict Typed Quarantine:
   - Negative, non-finite, missing, and duplicate records quarantined.
   - No silent repair or deletion.
4. Spatio-Temporal Split Leakage Prohibition:
   - Zero facility overlap between train and test sets.
   - Strict temporal causality: train records strictly precede test records.
5. Model Registry Audit Preservation:
   - Verifies transparent audit corrections on prior 16-row toy models.
   - Verifies simulation models are marked as benchmark simulations, not approved for pilot.
   - Verifies no unverified model can be labeled "approved for pilot" without human approval.
6. Model Serving & API Honesty:
   - default_trust_scorer() refuses to serve unverified models as real.
   - GET /model/status reports UNVERIFIED_AWAITING_FIELD_ATTESTATIONS and FILE PRESENT BUT UNVERIFIED.
   - GET /trust/queue reports SYNTHETIC_CAG_BENCHMARK and SYNTHETIC_TARGETING_QUEUE.
7. Repeatable Dry-Run Execution:
   - run_local_real_pipeline(dry_run=True) audits data without mutating registry.
"""
from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
import numpy as np
import pandas as pd
import pytest
from fastapi.testclient import TestClient

from tathyon.real_data_pipeline import (
    AUTHORIZED_ATTESTER_ROLES,
    MIN_INSPECTION_SECONDS,
    P6_MEDICINE_REL_ERR_THRESHOLD,
    P6_MEDICINE_USABLE_SHARE_FLOOR,
    RealDataIngestor,
    compute_file_sha256,
    extract_real_medicine_features,
    split_facility_and_time,
)
from tathyon.real_training import ModelRegistry, run_local_real_pipeline
from tathyon.trust_features import TRUST_FEATURES
from tathyon.verify import TrustScorer, default_trust_scorer, train_trust_scorer


# ---------------------------------------------------------------------------
# 1. DATA LINEAGE & PROVENANCE
# ---------------------------------------------------------------------------

def test_data_lineage_and_benchmark_detection():
    """Verify that data/real/dvdms_ledger.csv has documented SHA-256 and is identified as benchmark simulation."""
    csv_path = Path("data/real/dvdms_ledger.csv")
    assert csv_path.is_file(), "data/real/dvdms_ledger.csv must exist locally"

    sha = compute_file_sha256(csv_path)
    assert sha == "8229d3e4c0343d4faedc25749f99996dbaab16c0be3f75e859d275f0ff02fcd8"

    # Confirm it is generated by generate_real_pilot_data.py
    ingestor = RealDataIngestor()
    clean_df, manifest, quarantine = ingestor.validate_and_ingest(
        source_path=csv_path,
        source_name="DVDMS_Standard_Ledger_Export",
        source_owner="State Health Logistics Corporation (CGMSC/RMSCL)",
        license_str="Restricted Sovereign Government Data",
    )
    assert manifest.file_sha256 == sha
    assert manifest.valid_rows == 18000
    assert manifest.unique_facilities == 30
    assert manifest.labeled_rows == 369


# ---------------------------------------------------------------------------
# 2. LABEL PROVENANCE REFUSAL
# ---------------------------------------------------------------------------

def test_label_refusal_custodian_self_attestation():
    """Custodian self-attestation is strictly quarantined."""
    with tempfile.NamedTemporaryFile("w", suffix=".csv", delete=False) as f:
        f.write("facility_id,sku,date,reported_stock,is_materially_wrong,attester_role,is_custodian,seconds_spent,counted_present,counted_usable\n")
        f.write("FAC_01,MED_01,2026-08-01,100,1,district_drug_inspector,true,120.0,50.0,50.0\n")
        tmp_name = f.name

    try:
        ingestor = RealDataIngestor()
        clean_df, manifest, quarantine = ingestor.validate_and_ingest(
            source_path=tmp_name,
            source_name="Test_Self_Attestation",
            source_owner="Test",
            license_str="Test",
        )
        assert len(clean_df) == 0
        assert manifest.quarantined_rows == 1
        assert quarantine[0].error_type == "CUSTODIAN_SELF_ATTESTATION"
    finally:
        os.unlink(tmp_name)


def test_label_refusal_unauthorized_attester_role():
    """Attester role not in authorized list is strictly quarantined."""
    with tempfile.NamedTemporaryFile("w", suffix=".csv", delete=False) as f:
        f.write("facility_id,sku,date,reported_stock,is_materially_wrong,attester_role,is_custodian,seconds_spent,counted_present,counted_usable\n")
        f.write("FAC_01,MED_01,2026-08-01,100,1,intern_clerk,false,120.0,50.0,50.0\n")
        tmp_name = f.name

    try:
        ingestor = RealDataIngestor()
        clean_df, manifest, quarantine = ingestor.validate_and_ingest(
            source_path=tmp_name,
            source_name="Test_Unauthorized_Role",
            source_owner="Test",
            license_str="Test",
        )
        assert len(clean_df) == 0
        assert manifest.quarantined_rows == 1
        assert quarantine[0].error_type == "UNAUTHORIZED_ATTESTER_ROLE"
    finally:
        os.unlink(tmp_name)


def test_label_refusal_rubber_stamp_under_20_seconds():
    """Verification logged with under 20.0 seconds is flagged as rubber-stamping and quarantined."""
    with tempfile.NamedTemporaryFile("w", suffix=".csv", delete=False) as f:
        f.write("facility_id,sku,date,reported_stock,is_materially_wrong,attester_role,is_custodian,seconds_spent,counted_present,counted_usable\n")
        f.write("FAC_01,MED_01,2026-08-01,100,1,district_drug_inspector,false,12.5,50.0,50.0\n")
        tmp_name = f.name

    try:
        ingestor = RealDataIngestor()
        clean_df, manifest, quarantine = ingestor.validate_and_ingest(
            source_path=tmp_name,
            source_name="Test_Rubber_Stamp",
            source_owner="Test",
            license_str="Test",
        )
        assert len(clean_df) == 0
        assert manifest.quarantined_rows == 1
        assert quarantine[0].error_type == "RUBBER_STAMP_UNDER_TIME"
    finally:
        os.unlink(tmp_name)


def test_label_refusal_usable_exceeds_present():
    """Physical usable stock cannot exceed total physically present units."""
    with tempfile.NamedTemporaryFile("w", suffix=".csv", delete=False) as f:
        f.write("facility_id,sku,date,reported_stock,is_materially_wrong,attester_role,is_custodian,seconds_spent,counted_present,counted_usable\n")
        f.write("FAC_01,MED_01,2026-08-01,100,1,district_drug_inspector,false,120.0,50.0,75.0\n")
        tmp_name = f.name

    try:
        ingestor = RealDataIngestor()
        clean_df, manifest, quarantine = ingestor.validate_and_ingest(
            source_path=tmp_name,
            source_name="Test_Usable_Exceeds_Present",
            source_owner="Test",
            license_str="Test",
        )
        assert len(clean_df) == 0
        assert manifest.quarantined_rows == 1
        assert quarantine[0].error_type == "USABLE_EXCEEDS_PRESENT"
    finally:
        os.unlink(tmp_name)


def test_label_refusal_p6_threshold_contradiction():
    """Supplied label contradicting statutory P6 mathematical formula is quarantined."""
    # Reported 100, present 98 (relative error 2% < 15%), usable 98 (98% > 70%).
    # This is P6 = 0, but input claims is_materially_wrong = 1.
    with tempfile.NamedTemporaryFile("w", suffix=".csv", delete=False) as f:
        f.write("facility_id,sku,date,reported_stock,is_materially_wrong,attester_role,is_custodian,seconds_spent,counted_present,counted_usable\n")
        f.write("FAC_01,MED_01,2026-08-01,100,1,district_drug_inspector,false,120.0,98.0,98.0\n")
        tmp_name = f.name

    try:
        ingestor = RealDataIngestor()
        clean_df, manifest, quarantine = ingestor.validate_and_ingest(
            source_path=tmp_name,
            source_name="Test_P6_Contradiction",
            source_owner="Test",
            license_str="Test",
        )
        assert len(clean_df) == 0
        assert manifest.quarantined_rows == 1
        assert quarantine[0].error_type == "P6_THRESHOLD_CONTRADICTION"
    finally:
        os.unlink(tmp_name)


# ---------------------------------------------------------------------------
# 3. TYPED QUARANTINE INTEGRITY (NO SILENT REPAIR)
# ---------------------------------------------------------------------------

def test_quarantine_negative_and_invalid_quantities():
    """Negative or non-finite stock quantities are quarantined with typed reason."""
    with tempfile.NamedTemporaryFile("w", suffix=".csv", delete=False) as f:
        f.write("facility_id,sku,date,reported_stock\n")
        f.write("FAC_01,MED_01,2026-08-01,-50.0\n")
        f.write("FAC_01,MED_02,2026-08-01,corrupt_text\n")
        f.write("FAC_01,MED_03,2026-08-01,nan\n")
        f.write("FAC_01,MED_04,2026-08-01,150.0\n")
        tmp_name = f.name

    try:
        ingestor = RealDataIngestor()
        clean_df, manifest, quarantine = ingestor.validate_and_ingest(
            source_path=tmp_name,
            source_name="Test_Quarantine",
            source_owner="Test",
            license_str="Test",
        )
        assert len(clean_df) == 1
        assert manifest.valid_rows == 1
        assert manifest.quarantined_rows == 3
        err_types = [q.error_type for q in quarantine]
        assert "NEGATIVE_QUANTITY" in err_types
        assert "INVALID_NUMERIC_QTY" in err_types
        assert "NON_FINITE_QTY" in err_types
    finally:
        os.unlink(tmp_name)


def test_quarantine_duplicate_records():
    """Duplicate (facility, sku, date) observations are caught without silent overwrite."""
    with tempfile.NamedTemporaryFile("w", suffix=".csv", delete=False) as f:
        f.write("facility_id,sku,date,reported_stock\n")
        f.write("FAC_01,MED_01,2026-08-01,100.0\n")
        f.write("FAC_01,MED_01,2026-08-01,100.0\n")  # Exact duplicate
        tmp_name = f.name

    try:
        ingestor = RealDataIngestor()
        clean_df, manifest, quarantine = ingestor.validate_and_ingest(
            source_path=tmp_name,
            source_name="Test_Duplicates",
            source_owner="Test",
            license_str="Test",
        )
        assert len(clean_df) == 1
        assert manifest.quarantined_rows == 1
        assert quarantine[0].error_type == "DUPLICATE_RECORD"
    finally:
        os.unlink(tmp_name)


# ---------------------------------------------------------------------------
# 4. SPATIO-TEMPORAL SPLIT LEAKAGE PROHIBITION
# ---------------------------------------------------------------------------

def test_spatio_temporal_split_zero_leakage():
    """split_facility_and_time must guarantee ZERO facility overlap and strict temporal ordering."""
    dates = pd.date_range("2026-07-01", "2026-08-30")
    facilities = [f"FAC_{i:02d}" for i in range(10)]
    rows = []
    for fac in facilities:
        for d in dates:
            rows.append({
                "facility_id": fac,
                "date": d,
                "val": 1.0,
            })
    df = pd.DataFrame(rows)

    train_df, test_df, split_def = split_facility_and_time(
        df, test_facility_ratio=0.30, seed=20260928, temporal_split_quantile=0.80
    )

    # 1. Facility mutual exclusivity
    train_facs = set(train_df["facility_id"].unique())
    test_facs = set(test_df["facility_id"].unique())
    assert len(train_facs.intersection(test_facs)) == 0, "Test facilities must NEVER appear in training set"
    assert len(test_facs) == 3
    assert len(train_facs) == 7

    # 2. Temporal boundary
    if split_def.split_timestamp:
        cutoff = pd.Timestamp(split_def.split_timestamp)
        assert (train_df["date"] <= cutoff).all(), "Train set cannot observe records after temporal boundary"


# ---------------------------------------------------------------------------
# 5. MODEL REGISTRY AUDIT PRESERVATION
# ---------------------------------------------------------------------------

def test_model_registry_audit_preservation():
    """Prior registry history must preserve transparent audit corrections and revoke unverified claims."""
    registry = ModelRegistry()
    models = {m["model_id"]: m for m in registry.data.get("models", [])}

    # Verify toy 16-row models are marked revoked
    if "TATHYON-GBC-BASELINE-05755bea" in models:
        m = models["TATHYON-GBC-BASELINE-05755bea"]
        assert m.get("status") == "unverified (revoked)"
        assert m.get("human_approval_documented") is False
        assert "REVOKED" in m.get("audit_correction", "")

    if "TATHYON-GBC-REAL-PILOT-05755bea" in models:
        m = models["TATHYON-GBC-REAL-PILOT-05755bea"]
        assert m.get("status") in ["unverified (revoked)", "candidate"]
        assert m.get("human_approval_documented") is False
        assert m.get("status") != "approved for pilot"

    # Verify simulation benchmark model is marked not approved for pilot
    if "TATHYON-GBC-REAL-PILOT-8229d3e4" in models:
        m = models["TATHYON-GBC-REAL-PILOT-8229d3e4"]
        assert m.get("status") == "benchmark simulation (not approved for pilot)"
        assert m.get("human_approval_documented") is False


# ---------------------------------------------------------------------------
# 6. MODEL SERVING & API HONESTY
# ---------------------------------------------------------------------------

def test_default_trust_scorer_refuses_unverified_model():
    """default_trust_scorer() must refuse to serve unverified toy or simulation models."""
    scorer = default_trust_scorer()
    # Scorer must not claim to be a verified real pilot model
    assert getattr(scorer, "is_verified_real", False) is False
    assert "Synthetic" in getattr(scorer, "model_id", "Synthetic") or getattr(scorer, "train_rows", 0) > 1000


def test_api_model_status_honesty(api_client):
    """No model trained on real, human-attested labels exists, so none is served."""
    data = api_client.get("/api/model/status", headers=api_client.login("auditor")).json()
    assert data["trust_scorer_served"] is False
    assert data["status"] == "NOT_SERVED"
    assert "SYNTHETIC" in data["offline_benchmark"]


def test_api_trust_queue_is_empty_without_uploaded_data(api_client):
    """The operational queue never serves benchmark records: empty until real data is uploaded."""
    data = api_client.get("/api/trust/queue", headers=api_client.login("auditor")).json()
    assert data["rows"] == []
    assert data["environment"] == "REAL_DATA"


# ---------------------------------------------------------------------------
# 7. REPEATABLE DRY-RUN AUDIT
# ---------------------------------------------------------------------------

def test_dry_run_audit_pipeline_execution():
    """run_local_real_pipeline(dry_run=True) must be fully read-only."""
    from tathyon.real_training import DATA_CARD_PATH, EXCLUSION_SUMMARY_PATH, REGISTRY_PATH

    tracked_paths = [Path(DATA_CARD_PATH), Path(EXCLUSION_SUMMARY_PATH), Path(REGISTRY_PATH)]
    before = {path: path.read_bytes() if path.exists() else None for path in tracked_paths}
    quarantine_dir = Path("data/quarantine")
    quarantine_before = set(quarantine_dir.glob("*")) if quarantine_dir.exists() else set()

    res = run_local_real_pipeline(
        source_csv_path="data/real/dvdms_ledger.csv",
        dry_run=True,
        resource_module="medicine",
    )
    assert res["mode"] == "DRY_RUN"
    assert res["file_sha256"] == "8229d3e4c0343d4faedc25749f99996dbaab16c0be3f75e859d275f0ff02fcd8"
    assert res["is_simulation"] is True
    assert res["supervised_training_possible"] is False
    assert res["pipeline_status"] == "FILE PRESENT BUT UNVERIFIED"
    assert before == {path: path.read_bytes() if path.exists() else None for path in tracked_paths}
    assert quarantine_before == (set(quarantine_dir.glob("*")) if quarantine_dir.exists() else set())


def test_known_benchmark_file_cannot_be_fit_or_registered():
    """The generated benchmark's pseudo-labels must never create a model artifact."""
    from tathyon.real_training import DATA_CARD_PATH, EXCLUSION_SUMMARY_PATH, REGISTRY_PATH

    tracked_paths = [
        Path(DATA_CARD_PATH),
        Path(EXCLUSION_SUMMARY_PATH),
        Path(REGISTRY_PATH),
        Path("artifacts/models/trust_scorer_real_pilot.joblib"),
    ]
    before = {path: path.read_bytes() if path.exists() else None for path in tracked_paths}

    result = run_local_real_pipeline(
        source_csv_path="data/real/dvdms_ledger.csv",
        dry_run=False,
        resource_module="medicine",
    )

    assert result["status"] == "BENCHMARK_SIMULATION_TRAINING_BLOCKED"
    assert result["is_simulation"] is True
    assert result["supervised_training_conducted"] is False
    assert before == {path: path.read_bytes() if path.exists() else None for path in tracked_paths}


def test_missing_source_dry_run_writes_nothing(tmp_path, monkeypatch):
    """A dry-run with no input must not create cards, summaries, registries, or quarantine dirs."""
    import tathyon.real_training as training

    monkeypatch.setattr(training, "DATA_CARD_PATH", tmp_path / "real_data_card.json")
    monkeypatch.setattr(training, "EXCLUSION_SUMMARY_PATH", tmp_path / "exclusion_summary.json")
    monkeypatch.setattr(training, "REGISTRY_PATH", tmp_path / "model_registry.json")

    result = training.run_local_real_pipeline(
        source_csv_path=str(tmp_path / "missing.csv"),
        dry_run=True,
    )

    assert result["mode"] == "DRY_RUN"
    assert result["status"] == "AWAITING_FIELD_ATTESTATIONS"
    assert not list(tmp_path.iterdir())
