"""Versioned system prompts and tool JSON schemas for TATHYON's 6 Narrow AI Roles.

All outputs are strictly advisory with:
"AI suggestion — human decides."
"""

PROMPT_VERSION = "2.1.0"

ROLE_PROMPTS = {
    "ROLE_A_INTAKE": (
        "You are TATHYON Role A — Intake Extraction assistant. "
        "Your task is to transcribe photographed or scanned physical count sheets and stock registers from primary health centres. "
        "RULES:\n"
        "1. Transcribe ONLY numbers and text explicitly written by humans on the page. Do NOT count items or boxes.\n"
        "2. If any field is illegible, uncertain, or missing, set it to null. Never guess.\n"
        "3. Validate extracted records against the schema. If invalid, quarantine the row with a specific reason.\n"
        "4. You have NO authority to approve transfers, allocate resources, or mark stock as VERIFIED.\n"
        "5. Every response must be truthful, bounded, and include the disclaimer: 'AI suggestion — human decides.'\n"
    ),
    "ROLE_B_DATA_QUALITY": (
        "You are TATHYON Role B — Data Quality Triage assistant. "
        "Your task is to evaluate observations for potential errors, arithmetic violations, unit mismatches, "
        "reporting staleness, and anomalous changes. "
        "RULES:\n"
        "1. Inspect observations and historical baselines using your allowlisted tools.\n"
        "2. Output evidence-backed anomaly flags and recommend review priority for human supervisors.\n"
        "3. You must NOT alter or rewrite data, and you must NOT declare or accuse a facility of fraud.\n"
        "4. All findings are advisory. Always include: 'AI suggestion — human decides.'\n"
    ),
    "ROLE_C_FORECAST_EXPLAINER": (
        "You are TATHYON Role C — Demand Forecast Explainer. "
        "Your task is to explain deterministic statistical forecasts, risk scores, and trend drivers to authorized health officers in plain language. "
        "RULES:\n"
        "1. Explain inputs, historical time windows, uncertainty intervals, and data limitations using read tools.\n"
        "2. Do NOT compute or invent numbers. Use only the outputs from the deterministic forecasting engine.\n"
        "3. Highlight data freshness gaps and explain that forecasts do not imply certainty.\n"
        "4. Always include: 'AI suggestion — human decides.'\n"
    ),
    "ROLE_D_OPS_COPILOT": (
        "You are TATHYON Role D — District Operations Copilot. "
        "Your task is to provide bounded, read-only decision support to District Health Officers and logisticians. "
        "RULES:\n"
        "1. Answer ONLY from tool results. CITE relevant EVT IDs (e.g. [EVT-2026-000042]) for every factual claim.\n"
        "2. If data is missing or not returned by tools, answer plainly: 'I don't have that data.' Do NOT extrapolate.\n"
        "3. REFUSE any request to approve transfers, veto lines, dispatch stock, or allocate supplies. This is TATHYON's product safety policy; authority must be configured and verified under applicable department/state procedures.\n"
        "4. Always include: 'AI suggestion — human decides.'\n"
    ),
    "ROLE_E_ALLOCATION_EXPLAINER": (
        "You are TATHYON Role E — Allocation Plan Explainer. "
        "Your task is to explain deterministic CP-SAT optimization transfer plans to medical officers. "
        "RULES:\n"
        "1. Explain proposed donor/recipient pairs, quantities, routes, constraints, and why donors were rejected.\n"
        "2. The allocation plan is generated by the deterministic mathematical solver; you CANNOT edit, rank, approve, or execute it.\n"
        "3. Highlight donor safety floors (e.g. 14-day stock runway) and unverified stock gates.\n"
        "4. Always include: 'AI suggestion — human decides.'\n"
    ),
    "ROLE_F_FEDERATION_STEWARD": (
        "You are TATHYON Role F — Federation Model Steward. "
        "Your task is to explain model-round status, aggregation metrics, and anomaly pattern signatures across sovereign districts and BRICS partners. "
        "RULES:\n"
        "1. Explain participating nodes, model versions, validation PR-AUC, and structural anomaly patterns.\n"
        "2. ZERO RAW DATA PRINCIPLE: You cannot access or reveal facility-level inventory, patient records, or raw transaction logs.\n"
        "3. You cannot trigger training rounds, publish models, or modify federation policies.\n"
        "4. Always include: 'AI suggestion — human decides.'\n"
    ),
}

TOOL_DECLARATIONS = {
    "extract_count_sheet": {
        "name": "extract_count_sheet",
        "description": "Extracts structured count sheet fields from photographed document using GenAI vision.",
        "parameters": {
            "type": "object",
            "properties": {
                "document_reference": {"type": "string", "description": "Document ID or file path"},
                "mime_type": {"type": "string", "description": "MIME type of document"},
            },
            "required": ["document_reference"],
        },
    },
    "validate_schema": {
        "name": "validate_schema",
        "description": "Validates candidate extraction against mathematical and schema invariants.",
        "parameters": {
            "type": "object",
            "properties": {
                "candidate": {"type": "object", "description": "Extracted candidate dictionary"},
            },
            "required": ["candidate"],
        },
    },
    "quarantine_row": {
        "name": "quarantine_row",
        "description": "Quarantines anomalous row into audit ledger and flags human supervisor review.",
        "parameters": {
            "type": "object",
            "properties": {
                "candidate": {"type": "object", "description": "Raw candidate data"},
                "reason": {"type": "string", "description": "Specific validation failure reason"},
            },
            "required": ["candidate", "reason"],
        },
    },
    "file_attestation_record": {
        "name": "file_attestation_record",
        "description": "Files validated intake record as a staged claim record in audit ledger.",
        "parameters": {
            "type": "object",
            "properties": {
                "validated_record": {"type": "object", "description": "Validated clean record"},
                "attester_id": {"type": "string", "description": "Attesting witness ID"},
            },
            "required": ["validated_record"],
        },
    },
    "read_observation": {
        "name": "read_observation",
        "description": "Reads raw reported observation for a facility and resource.",
        "parameters": {
            "type": "object",
            "properties": {
                "facility_id": {"type": "string", "description": "Facility identifier"},
                "resource_key": {"type": "string", "description": "SKU, Bed, or Personnel identifier"},
            },
            "required": ["facility_id", "resource_key"],
        },
    },
    "compare_history": {
        "name": "compare_history",
        "description": "Compares observation against historical baseline and peer facilities.",
        "parameters": {
            "type": "object",
            "properties": {
                "facility_id": {"type": "string", "description": "Facility identifier"},
                "resource_key": {"type": "string", "description": "Resource identifier"},
                "lookback_days": {"type": "integer", "description": "Trailing days to inspect"},
            },
            "required": ["facility_id", "resource_key"],
        },
    },
    "calculate_quality_flags": {
        "name": "calculate_quality_flags",
        "description": "Calculates statistical and tier-1 quality flags for an observation.",
        "parameters": {
            "type": "object",
            "properties": {
                "observation": {"type": "object", "description": "Observation record"},
            },
            "required": ["observation"],
        },
    },
    "create_review_recommendation": {
        "name": "create_review_recommendation",
        "description": "Creates an advisory review priority ticket for human supervisor review.",
        "parameters": {
            "type": "object",
            "properties": {
                "facility_id": {"type": "string", "description": "Target facility"},
                "resource_key": {"type": "string", "description": "Target resource"},
                "anomaly_flags": {"type": "array", "items": {"type": "string"}, "description": "List of detected flags"},
                "recommended_priority": {"type": "string", "enum": ["HIGH", "MEDIUM", "LOW"], "description": "Advisory priority"},
                "rationale": {"type": "string", "description": "Evidence-backed rationale"},
            },
            "required": ["facility_id", "resource_key", "anomaly_flags", "recommended_priority", "rationale"],
        },
    },
    "read_forecast": {
        "name": "read_forecast",
        "description": "Reads deterministic statistical forecast for facility and SKU.",
        "parameters": {
            "type": "object",
            "properties": {
                "facility_id": {"type": "string", "description": "Facility ID"},
                "sku_id": {"type": "string", "description": "Medicine SKU"},
            },
            "required": ["facility_id", "sku_id"],
        },
    },
    "read_feature_summary": {
        "name": "read_feature_summary",
        "description": "Reads causal feature weights and signals driving risk score.",
        "parameters": {
            "type": "object",
            "properties": {
                "facility_id": {"type": "string", "description": "Facility ID"},
                "sku_id": {"type": "string", "description": "Medicine SKU"},
            },
            "required": ["facility_id", "sku_id"],
        },
    },
    "read_data_freshness": {
        "name": "read_data_freshness",
        "description": "Reads timestamp and days elapsed since last physical attestation.",
        "parameters": {
            "type": "object",
            "properties": {
                "facility_id": {"type": "string", "description": "Facility ID"},
            },
            "required": ["facility_id"],
        },
    },
    "explain_model_output": {
        "name": "explain_model_output",
        "description": "Summarizes statistical backtest model (Croston/TSB/Seasonal Naive) parameters.",
        "parameters": {
            "type": "object",
            "properties": {
                "facility_id": {"type": "string", "description": "Facility ID"},
                "sku_id": {"type": "string", "description": "Medicine SKU"},
            },
            "required": ["facility_id", "sku_id"],
        },
    },
    "query_trust_queue": {
        "name": "query_trust_queue",
        "description": "Inspects target verification queue for prioritized facilities.",
        "parameters": {
            "type": "object",
            "properties": {
                "budget_slots": {"type": "integer", "description": "Field visit cost slots"},
                "limit": {"type": "integer", "description": "Maximum records to return"},
            },
        },
    },
    "get_facility_detail": {
        "name": "get_facility_detail",
        "description": "Looks up facility metadata, tier, reported stock, and safety floors.",
        "parameters": {
            "type": "object",
            "properties": {
                "facility_id": {"type": "string", "description": "Facility ID"},
            },
            "required": ["facility_id"],
        },
    },
    "search_audit_log": {
        "name": "search_audit_log",
        "description": "Searches immutable SHA-256 event ledger.",
        "parameters": {
            "type": "object",
            "properties": {
                "facility_id": {"type": "string", "description": "Facility filter"},
                "event_type": {"type": "string", "description": "Event type filter"},
                "query": {"type": "string", "description": "Text query"},
            },
        },
    },
    "get_allocation_plan": {
        "name": "get_allocation_plan",
        "description": "Retrieves active CP-SAT allocation plan proposal.",
        "parameters": {
            "type": "object",
            "properties": {
                "plan_id": {"type": "string", "description": "Plan ID"},
            },
        },
    },
    "explain_event": {
        "name": "explain_event",
        "description": "Explains cryptographic SHA-256 event block and chain integrity.",
        "parameters": {
            "type": "object",
            "properties": {
                "event_id_or_hash": {"type": "string", "description": "Event ID or block hash"},
            },
            "required": ["event_id_or_hash"],
        },
    },
    "read_allocation_plan": {
        "name": "read_allocation_plan",
        "description": "Reads proposed transfers and shortfall quantities from active CP-SAT plan.",
        "parameters": {
            "type": "object",
            "properties": {
                "plan_id": {"type": "string", "description": "Plan identifier"},
            },
        },
    },
    "read_constraints": {
        "name": "read_constraints",
        "description": "Reads donor safety floors and vehicle capacity limits enforced on plan.",
        "parameters": {
            "type": "object",
            "properties": {
                "plan_id": {"type": "string", "description": "Plan identifier"},
            },
        },
    },
    "read_federation_status": {
        "name": "read_federation_status",
        "description": "Reads active participating districts, model round, and synchronization state.",
        "parameters": {
            "type": "object",
            "properties": {
                "round_id": {"type": "string", "description": "Federation round ID"},
            },
        },
    },
    "read_model_card": {
        "name": "read_model_card",
        "description": "Reads model specifications, training date, PR-AUC, and anti-leakage invariants.",
        "parameters": {
            "type": "object",
            "properties": {
                "model_name": {"type": "string", "description": "Model identifier"},
            },
        },
    },
    "read_aggregate_metrics": {
        "name": "read_aggregate_metrics",
        "description": "Reads aggregate macro metrics (e.g. headline verified days averted across nodes).",
        "parameters": {
            "type": "object",
            "properties": {
                "metric_group": {"type": "string", "description": "Metric category"},
            },
        },
    },
}
